all:
  hosts:
    node1:
      ansible_host: 10.100.1.161
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.161
      access_ip: 10.100.1.161
    node2:
      ansible_host: 10.100.1.162
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.162
      access_ip: 10.100.1.162
    node3:
      ansible_host: 10.100.1.163
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.163
      access_ip: 10.100.1.163
    node4:
      ansible_host: 10.100.1.164
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.164
      access_ip: 10.100.1.164
    node5:
      ansible_host: 10.100.1.165
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.165
      access_ip: 10.100.1.165
    node6:
      ansible_host: 10.100.1.166
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.166
      access_ip: 10.100.1.166
    node7:
      ansible_host: 10.100.1.170
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.170
      access_ip: 10.100.1.170
    node8:
      ansible_host: 10.100.1.171
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.171
      access_ip: 10.100.1.171
    node9:
      ansible_host: 10.100.1.172
      ansible_user: root
      become_method: su
      become_flags: "-"
      ip: 10.100.1.172
      access_ip: 10.100.1.172      
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
        node7:
        node8:
        node9:
    etcd:
      hosts:
        node7:
        node8:
        node9:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
